version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwordd
    volumes:
      - ./data:/data/db
    networks:
      - lab-network

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb_data:

networks:
  lab-network:
    driver: bridge  # Use the bridge network driver (default for single-host networking)